---
- name: wait for prometheus up
  wait_for:
    host: "{{ prometheus_listen_host }}"
    port: "{{ prometheus_listen_port }}"

- name: check prometheus service
  uri:
    url: http://{{ prometheus_listen_host|ipwrap }}:{{ prometheus_listen_port }}/api/v1/status/flags
