---
- name: ensure etc folder
  file:
    path: "{{ item }}"
    recurse: true
    state: directory
  with_items:
    - "{{ prometheus_etc_path }}"
    - "{{ prometheus_etc_path }}/rules"

- name: ensure data folder
  file:
    path: "{{ prometheus_data_path }}"
    recurse: true
    state: directory
  when:
    - prometheus_data_path.startswith('/')

- name: copy prometheus.yml file
  template:
    src: "{{ item }}"
    dest: "{{ prometheus_etc_path }}/prometheus.yml"
  with_first_found:
    - files:
        - "{{ prometheus_yaml_file }}.j2"
      paths:
        - "{{ playbook_dir }}/templates/"
        - "{{ playbook_dir }}/templates/{{ role_name }}"
        - "{{ role_path }}/templates"
  notify:
    - check configure files
    - reload prometheus service

- name: copy rules files
  template:
    src: "{{ item }}"
    dest: "{{ prometheus_etc_path }}/rules/{{ item|basename }}"
  with_items: "{{ prometheus_rule_files }}"
  notify:
    - check configure rules
    - reload prometheus service
