---
- name: ensure folder
  file:
    path: "{{ prometheus_bin_path }}"
    state: directory

- name: Download prometheus packages
  get_url:
    url: "{{ prometheus_download_url }}"
    dest: /tmp/{{ prometheus_filename }}
    checksum: "{{ prometheus_checksum }}"
  register: download_prometheus

- name: unpack the package
  unarchive:
    src: /tmp/{{ prometheus_filename }}
    dest: /opt/prometheus
    owner: root
    group: root
    remote_src: true
    extra_opts:
      - --strip-components=1
  when:
    - download_prometheus is changed
