---
- include: "install.yml"

- include: "config.yml"

- name: flush handlers
  meta: flush_handlers

- name: ensure prometheus service is enabled
  systemd:
    name: prometheus
    state: started
    enabled: true
  ignore_errors: true
# vim:ft=yaml
