---
- name: check configure files
  docker_container:
    name: "{{ prometheus_container_name }}_check_config"
    image: "{{ prometheus_image_fullname }}"
    entrypoint:
      - /bin/promtool
    command:
      - check
      - config
      - /etc/prometheus/prometheus.yml
    detach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ prometheus_etc_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_path }}:/prometheus"

- name: check configure rules
  docker_container:
    name: "{{ prometheus_container_name }}_check_rules"
    image: "{{ prometheus_image_fullname }}"
    entrypoint:
      - /bin/promtool
    command:
      - check
      - rules
      - /etc/prometheus/rules/*.yml
    detach: false
    volume:
      - /etc/localtime:/etc/localtime:ro
      - "{{ prometheus_etc_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_path }}:/prometheus"

- name: restart prometheus service
  docker_container:
    name: "{{ prometheus_container_name }}"
    restart: true

- name: reload prometheus service
  docker_container:
    name: "{{ prometheus_container_name }}"
    force_kill: true
    kill_signal: SIGHUP
