---
- name: check configure files
  docker_container:
    name: prometheus_check_config
    image: "{{ prometheus_image_fullname }}"
    entrypoint:
    command:
      - /bin/prometheus
      - check
      - config
      - /etc/prometheus/prometheus.yml
    detach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ prometheus_etc_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_path }}:/var/lib/prometheus"

- name: check configure rules
  docker_container:
    name: prometheus_check_config
    image: "{{ prometheus_image_fullname }}"
    entrypoint:
    commands:
      - /bin/prometheus
      - check
      - rules
      - /etc/prometheus/rules/*
    detach: false
    volume:
      - /etc/localtime:/etc/localtime:ro
      - "{{ prometheus_etc_path }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "{{ prometheus_data_path }}:/var/lib/prometheus"

- name: restart prometheus service
  docker_container:
    name: prometheus
    restart: true

- name: reload prometheus service
  docker_container:
    name: prometheus
    force_kill: true
    kill_signal: SIGHUP
