#!/bin/bash

#URL=https://github.com/prometheus/prometheus/releases/download/v2.5.0-rc.2/sha256sums.txt
BASE_URL=https://github.com/prometheus/prometheus/releases/download/

ME=$0
CUR_DIR=$(dirname $(readlink -f $ME))
PROJECT_ROOT=$(dirname ${CUR_DIR})

VERSIONS=(
    2.4.2
    2.4.3
    )

for version in ${VERSIONS[@]}; do
    dest=${PROJECT_ROOT}/vars/$version.sha256sums.yml
    echo --- > $dest
    curl -L $BASE_URL/v${version}/sha256sums.txt | sed -r 's/(\S+)\s+(\S+)/\2: sha256:\1/' >> $dest
done
