#!/bin/bash

#URL=https://github.com/prometheus/prometheus/releases/download/v2.5.0-rc.2/sha256sums.txt
BASE_URL=https://github.com/prometheus/prometheus/releases/download/

ME=$0
CUR_DIR=$(dirname $(readlink -f $ME))
PROJECT_ROOT=$(dirname ${CUR_DIR})

tags=$(curl https://api.github.com/repos/prometheus/prometheus/git/refs/tags | awk '/"ref"/')

VERSIONS=(
    v2.0.0
    v2.1.0
    v2.2.0
    v2.2.1
    v2.3.0
    v2.3.1
    v2.3.2
    v2.4.0
    v2.4.1
    v2.4.2
    v2.4.3
    v2.5.0
    v2.6.0
    v2.6.1
    v2.7.0
    v2.7.1
    v2.7.2
    v2.8.0
    v2.8.1
    v2.9.0
    v2.9.1
    v2.9.2
    v2.10.0
    )

for version in ${VERSIONS[@]}; do
    dest=${PROJECT_ROOT}/vars/$version.sha256sums.yml
    echo --- > $dest
    curl -L $BASE_URL/${version}/sha256sums.txt | sed -r 's/(\S+)\s+(\S+)/\2: sha256:\1/' >> $dest
done
