---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create molecule instance(s)
      lxc_container:
        name: "{{ item.name }}"
        container_log: false
        template: "{{ item.template }}"
        state: started
        template_options: "{{ item.template_options }}"
        container_command: "{{ item.container_command }}"
      with_items: "{{ molecule_yml.platforms }}"
