---
- name: Converge
  hosts: all
  tasks:
    - name: check sentinel file
      stat:
        path: /tmp/prometheus_latest_installed
      register: check_latest

    - name: install prometheus service
      vars:
        prometheus_version: 2.4.3
        download_mode: remote
      include_role:
        name: ansible-prometheus-role
      when:
        - not check_latest.stat.exists

    - name: upgrade prometheus service
      vars:
        prometheus_version: 2.5.0
        download_mode: locally
        prometheus_runas_user: prometheus
      include_role:
        name: ansible-prometheus-role

    - name: add sentinel file
      copy:
        content: ""
        dest: /tmp/prometheus_latest_installed
